# Generated by Django 3.1.4 on 2021-02-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
