# Generated by Django 3.1.4 on 2021-02-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='routiney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=5)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
