# Generated by Django 3.1.4 on 2021-03-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='prority',
            new_name='priority',
        ),
    ]
