# Generated by Django 3.1.4 on 2021-04-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20210309_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('low', 'low')], max_length=6),
        ),
        migrations.AlterField(
            model_name='help',
            name='request',
            field=models.CharField(max_length=20),
        ),
    ]
