# Generated by Django 3.1.4 on 2021-04-04 13:37

import django.core.validators
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100)),
                ('mod_code', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(9)])),
                ('description', models.TextField()),
                ('credit', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('file', models.FileField(blank=True, upload_to='files')),
                ('url', embed_video.fields.EmbedVideoField(blank=True)),
            ],
        ),
    ]
