# Generated by Django 3.1.4 on 2021-01-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('Year1', 'Year1'), ('Year2', 'Year2'), ('Year3', 'Year3')], max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
