# Generated by Django 3.1.4 on 2021-01-17 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210116_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='mod_code',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(9)]),
        ),
    ]
