# Generated by Django 3.1.4 on 2021-01-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210117_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='credit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
